### ISSUE TITLE
Store credentials in the GitHub Secrets for the `.env.local` file

### ISSUE THREAD

**Issue by ZU3AIRE** [ZU3AIRE/mark-me#48]
Modify the project so the keys are accessed from secure secret store for the `.env.local` file 
``` env
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=********************************
CLERK_SECRET_KEY=********************************
```

and remove `.env.local` from the `.gitignore`

**Comment by muhammad-mousa** [comment]
I cannot add the secret key and variables in the Repo due to some access issues.
#### How to add secret key and environment variables in github
[Add Secret Key](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions)


### This is my Repo 
![image](https://github.com/user-attachments/assets/21aef191-0ac0-48ce-8bf7-6c2f585b161a)

### In mark-me
![image](https://github.com/user-attachments/assets/fc2b2847-29c0-4aaa-9606-40a5dae714d4)

So, assigning this to you.
